// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc5xaPpGDs9qnJPhFITjMG5_TlhSDGwKs',
    appId: '1:209554004575:web:e4457c2caaf1de8f50d9ea',
    messagingSenderId: '209554004575',
    projectId: 'authtut-511f5',
    authDomain: 'authtut-511f5.firebaseapp.com',
    storageBucket: 'authtut-511f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3O3zD52HBA13_kQaQ2aLC6_1D6y1NApY',
    appId: '1:209554004575:android:c55b763755930b8950d9ea',
    messagingSenderId: '209554004575',
    projectId: 'authtut-511f5',
    storageBucket: 'authtut-511f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcLY9f-giQyWWXrw7BmXNyh41dh9Q5GQ',
    appId: '1:209554004575:ios:0bf3b3693de7b32f50d9ea',
    messagingSenderId: '209554004575',
    projectId: 'authtut-511f5',
    storageBucket: 'authtut-511f5.appspot.com',
    iosBundleId: 'com.example.log',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjcLY9f-giQyWWXrw7BmXNyh41dh9Q5GQ',
    appId: '1:209554004575:ios:411394bda884873750d9ea',
    messagingSenderId: '209554004575',
    projectId: 'authtut-511f5',
    storageBucket: 'authtut-511f5.appspot.com',
    iosBundleId: 'com.example.log.RunnerTests',
  );
}
